// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CacheService 缓存清理服务，作为 Wails v3 服务暴露给前端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * AnalyzeWinSxS 分析 Windows 组件存储（WinSxS），调用 dism /AnalyzeComponentStore
 * 注：耗时可达数分钟，建议在后台任务中使用；保留供高级用途
 */
export function AnalyzeWinSxS(): $CancellablePromise<models$0.WinSxSAnalysis> {
    return $Call.ByID(1179312016);
}

/**
 * CleanCache 清理选中的缓存分类（按分类名匹配）
 */
export function CleanCache(names: string[] | null): $CancellablePromise<models$0.CleanResult[] | null> {
    return $Call.ByID(327386743, names);
}

/**
 * CleanCacheItems 针对性清理：删除勾选的具体条目（文件或整个目录）
 */
export function CleanCacheItems(categoryName: string, itemPaths: string[] | null): $CancellablePromise<models$0.CleanResult> {
    return $Call.ByID(3897167065, categoryName, itemPaths);
}

/**
 * CleanOSUpgradeRemnants 清理给定的升级残留路径（白名单校验后夺所有权并删除）。
 * 逐目录：先 takeown 夺所有权 → icacls 授权 Administrators 完全控制 → os.RemoveAll。
 * 删除失败（文件被占用等）不影响其它目录。
 */
export function CleanOSUpgradeRemnants(paths: string[] | null): $CancellablePromise<models$0.OSCleanItemResult[] | null> {
    return $Call.ByID(1989185503, paths);
}

/**
 * GetWinSxSStatus 查询 WinSxS 后台清理状态（未启动时返回零值状态）
 */
export function GetWinSxSStatus(): $CancellablePromise<models$0.WinSxSCleanStatus> {
    return $Call.ByID(1284994118);
}

/**
 * ScanCache 扫描所有缓存分类，计算各路径占用
 */
export function ScanCache(): $CancellablePromise<models$0.CacheCategory[] | null> {
    return $Call.ByID(293061175);
}

/**
 * ScanCacheDetails 查看指定缓存分类的详细内容（各路径顶层条目，按大小降序）
 */
export function ScanCacheDetails(categoryName: string): $CancellablePromise<models$0.CacheDetailPath[] | null> {
    return $Call.ByID(537584191, categoryName);
}

/**
 * ScanOSUpgradeRemnants 扫描系统盘下的升级残留并统计占用。
 * 仅返回真实存在的目录；大小用并发 DirSize 计算，Windows.old 较大时耗时若干秒。
 */
export function ScanOSUpgradeRemnants(): $CancellablePromise<models$0.OSUpgradeRemnant[] | null> {
    return $Call.ByID(1381021599);
}

/**
 * StartWinSxSClean 后台启动 WinSxS 组件存储清理（dism /StartComponentCleanup）。
 * 立即返回，实际清理在后台 goroutine 中执行，前端可通过 GetWinSxSStatus 查询进度。
 * 需要管理员权限；耗时可能达数十分钟，期间不阻塞界面。
 */
export function StartWinSxSClean(): $CancellablePromise<models$0.WinSxSCleanStatus> {
    return $Call.ByID(500525369);
}

/**
 * StartWinSxSCleanResetBase 后台启动 WinSxS 激进清理（dism /StartComponentCleanup /ResetBase）。
 * 相比标准清理额外删除所有历史版本组件，释放更多空间，但「还原此 Windows 安装 / 组件回滚」将不可用，
 * 属破坏性操作——前端须二次确认后调用。状态/轮询/接口与标准清理完全共用。
 */
export function StartWinSxSCleanResetBase(): $CancellablePromise<models$0.WinSxSCleanStatus> {
    return $Call.ByID(3437117697);
}
