// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupEntry 清理备份记录（用于恢复）
 */
export interface BackupEntry {
    "id": string;
    "name": string;
    "ruleType": string;
    "riskLevel": string;
    "time": string;

    /**
     * HKLM | HKCU
     */
    "regHive"?: string;

    /**
     * 注册表键路径
     */
    "regKey"?: string;

    /**
     * 值名
     */
    "regValue"?: string;

    /**
     * 原值数据
     */
    "regData"?: string;

    /**
     * 原文件/目录路径
     */
    "origPath"?: string;

    /**
     * 备份后的路径
     */
    "backedPath"?: string;

    /**
     * 服务名
     */
    "serviceName"?: string;

    /**
     * 服务原启动类型
     */
    "serviceStart"?: number;

    /**
     * 计划任务名
     */
    "taskName"?: string;

    /**
     * 计划任务备份 XML
     */
    "taskXML"?: string;
}
