// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RogueService 流氓软件清理服务，作为 Wails v3 服务暴露给前端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanRogue 清理选中项并记录备份
 */
export function CleanRogue(ids: string[] | null): $CancellablePromise<models$0.RogueCleanResult[] | null> {
    return $Call.ByID(3946819275, ids);
}

/**
 * GetBackups 列出所有可恢复的清理备份
 */
export function GetBackups(): $CancellablePromise<$models.BackupEntry[] | null> {
    return $Call.ByID(2399284493);
}

/**
 * GetBlacklistInfo 返回当前黑名单状态（条目数/更新时间/本地目录）
 */
export function GetBlacklistInfo(): $CancellablePromise<models$0.BlacklistInfo> {
    return $Call.ByID(3803798953);
}

/**
 * RestoreRogue 按 ID 恢复已清理项
 */
export function RestoreRogue(ids: string[] | null): $CancellablePromise<models$0.RogueCleanResult[] | null> {
    return $Call.ByID(3901933222, ids);
}

/**
 * ScanRogue 扫描流氓/推广软件组件
 * 覆盖：启动项/启动文件夹/服务/计划任务/浏览器扩展/已装软件/黑名单目录/
 *      运行中进程/Shell 扩展注入点
 */
export function ScanRogue(): $CancellablePromise<models$0.RogueItem[] | null> {
    return $Call.ByID(2585258155);
}

/**
 * UpdateBlacklist 从远端下载最新黑名单并热加载（gitee softcnkiller/data）
 */
export function UpdateBlacklist(): $CancellablePromise<models$0.BlacklistUpdateResult> {
    return $Call.ByID(1818920218);
}
