// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    BlacklistFileInfo,
    BlacklistInfo,
    BlacklistUpdateResult,
    CacheCategory,
    CacheDetailItem,
    CacheDetailPath,
    CleanResult,
    DiskScanResult,
    DriveInfo,
    FileNode,
    MigratableApp,
    RogueCleanResult,
    RogueItem,
    ScanOptions,
    UpdateInfo,
    WinSxSAnalysis,
    WinSxSCleanStatus
} from "./models.js";
