// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BlacklistFileInfo 单个黑名单文件的更新结果
 */
export interface BlacklistFileInfo {
    /**
     * 文件名
     */
    "name": string;

    /**
     * 条目数
     */
    "count": number;

    /**
     * 是否成功
     */
    "ok": boolean;

    /**
     * 失败原因
     */
    "err": string;
}

/**
 * BlacklistInfo 当前黑名单状态
 */
export interface BlacklistInfo {
    /**
     * 目录名黑名单条数
     */
    "dirs": number;

    /**
     * 相对路径黑名单条数
     */
    "paths": number;

    /**
     * 签名黑名单条数
     */
    "signs": number;

    /**
     * 白名单条数
     */
    "white": number;

    /**
     * 本地黑名单更新时间（空=使用内置）
     */
    "localTime": string;

    /**
     * 本地黑名单目录
     */
    "localDir": string;
}

/**
 * BlacklistUpdateResult 黑名单在线更新结果
 */
export interface BlacklistUpdateResult {
    /**
     * 更新时间
     */
    "time": string;

    /**
     * 各文件结果
     */
    "files": BlacklistFileInfo[] | null;
}

/**
 * CacheCategory 缓存分类，用于前端展示与选择
 */
export interface CacheCategory {
    /**
     * 分类名称
     */
    "name": string;

    /**
     * 该分类包含的缓存路径（已解析环境变量）
     */
    "paths": string[] | null;

    /**
     * 占用空间（字节）
     */
    "size": number;

    /**
     * 文件数量
     */
    "fileCount": number;

    /**
     * 默认是否选中
     */
    "selected": boolean;

    /**
     * 路径是否存在（存在才可扫描/清理）
     */
    "exists": boolean;

    /**
     * 是否智能识别型分类（升级残留等，需专用扫描）
     */
    "special": boolean;

    /**
     * 是否需管理员权限（系统级目录）
     */
    "admin": boolean;

    /**
     * 纯数据型分类（聊天记录/办公文档），禁止清理，仅提示迁移
     */
    "dataOnly": boolean;

    /**
     * MigrateHint 数据保护型分类的迁移建议（DataOnly=true 时展示，告知用户如何安全释放空间）
     */
    "migrateHint": string;

    /**
     * 分类说明
     */
    "desc": string;
}

/**
 * CacheDetailItem 缓存目录下的单个条目（文件或目录）
 */
export interface CacheDetailItem {
    /**
     * 名称
     */
    "name": string;

    /**
     * 完整路径
     */
    "path": string;

    /**
     * 占用（目录为递归总大小）
     */
    "size": number;

    /**
     * 是否目录
     */
    "isDir": boolean;

    /**
     * 修改时间
     */
    "modTime": string;

    /**
     * Empty 目录条目：整棵子树无任何文件（仅空目录层级），可安全删除。
     * 用于数据保护分类：非空目录禁止清理，但空壳目录允许删除。
     */
    "empty": boolean;
}

/**
 * CacheDetailPath 单个缓存路径的详情
 */
export interface CacheDetailPath {
    /**
     * 缓存路径
     */
    "path": string;

    /**
     * 路径总占用
     */
    "size": number;

    /**
     * 文件数
     */
    "fileCount": number;

    /**
     * 顶层条目（前 N 大）
     */
    "items": CacheDetailItem[] | null;
}

/**
 * CleanResult 单分类清理结果
 */
export interface CleanResult {
    /**
     * 分类名称
     */
    "category": string;

    /**
     * 释放空间（字节）
     */
    "freedBytes": number;

    /**
     * 成功删除的文件/目录数
     */
    "fileCount": number;

    /**
     * 失败项说明
     */
    "errors": string[] | null;
}

/**
 * DiskScanResult 磁盘扫描结果（多引擎组合）
 */
export interface DiskScanResult {
    /**
     * 实际使用的引擎: mft | walk
     */
    "engine": string;

    /**
     * 文件树（截断版）
     */
    "node": FileNode | null;

    /**
     * 耗时（毫秒）
     */
    "duration": number;

    /**
     * 提示（如引擎回退说明）
     */
    "message": string;
}

/**
 * DriveInfo 逻辑磁盘信息
 */
export interface DriveInfo {
    /**
     * 盘符，如 C:
     */
    "name": string;

    /**
     * 总容量（字节）
     */
    "total": number;

    /**
     * 已用（字节）
     */
    "used": number;

    /**
     * 可用（字节）
     */
    "free": number;
}

/**
 * FileNode 文件树节点
 */
export interface FileNode {
    /**
     * 名称
     */
    "name": string;

    /**
     * 完整路径
     */
    "path": string;

    /**
     * 占用（字节）
     */
    "size": number;

    /**
     * 是否目录
     */
    "isDir": boolean;

    /**
     * 子节点（仅目录）
     */
    "children"?: (FileNode | null)[] | null;
}

/**
 * MigratableApp 可迁移的应用目录
 */
export interface MigratableApp {
    /**
     * 应用名
     */
    "name": string;

    /**
     * 当前路径
     */
    "path": string;

    /**
     * 占用空间
     */
    "size": number;

    /**
     * 文件数
     */
    "fileCount": number;

    /**
     * 建议迁移目标
     */
    "target": string;
}

/**
 * OSCleanItemResult 单个系统升级残留清理结果
 */
export interface OSCleanItemResult {
    /**
     * 展示名
     */
    "name": string;

    /**
     * 完整路径
     */
    "path": string;

    /**
     * 是否清理成功
     */
    "success": boolean;

    /**
     * 释放空间（字节）
     */
    "freedBytes": number;

    /**
     * 失败说明
     */
    "error": string;
}

/**
 * OSUpgradeRemnant Windows 系统升级残留项（$WINDOWS.~BT / ~BS / ~WS / Windows.old）
 */
export interface OSUpgradeRemnant {
    /**
     * 展示名
     */
    "name": string;

    /**
     * 完整路径
     */
    "path": string;

    /**
     * 占用（字节）
     */
    "size": number;

    /**
     * 文件数
     */
    "fileCount": number;

    /**
     * 是否需要管理员（系统区，恒为 true）
     */
    "needsAdmin": boolean;
}

/**
 * RogueCleanResult 清理结果
 */
export interface RogueCleanResult {
    /**
     * 对应 RogueItem.ID
     */
    "id": string;

    /**
     * 是否成功
     */
    "ok": boolean;

    /**
     * 失败原因
     */
    "errMsg": string;
}

/**
 * RogueItem 流氓软件扫描结果项
 */
export interface RogueItem {
    /**
     * 唯一 ID（用于清理）
     */
    "id": string;

    /**
     * 软件名
     */
    "name": string;

    /**
     * 匹配类型: registry | file | service | task | extension | installed | startup | process | shellex | browser | hosts | shortcut
     */
    "ruleType": string;

    /**
     * 位置描述
     */
    "location": string;

    /**
     * 具体路径/注册表值/服务名/任务名
     */
    "path": string;

    /**
     * 注册表值数据/显示名（如有）
     */
    "value": string;

    /**
     * 修复后的目标值（Action=repair 时应用，如 Userinit 系统默认值）
     */
    "repairValue": string;

    /**
     * high | medium | low
     */
    "riskLevel": string;

    /**
     * 说明
     */
    "detail": string;

    /**
     * 影响说明（用户可感知的行为）
     */
    "impact": string;

    /**
     * 处理方式: remove | disable_service | disable_task | remove_extension | repair | hint | kill
     */
    "action": string;

    /**
     * 是否选中清理
     */
    "selected": boolean;

    /**
     * 相关进程是否正在运行（需先终止）
     */
    "running": boolean;

    /**
     * 相关进程 PID（如有）
     */
    "pid": number;
}

/**
 * ScanOptions 磁盘扫描参数
 */
export interface ScanOptions {
    /**
     * 扫描根路径
     */
    "path": string;

    /**
     * 最大深度（0 表示默认 3）
     */
    "maxDepth": number;

    /**
     * 每层保留的最大子节点数（0 表示默认 10）
     */
    "topN": number;

    /**
     * 扫描引擎: auto | mft | walk
     */
    "engine": string;
}

/**
 * UpdateInfo 版本检查结果
 */
export interface UpdateInfo {
    /**
     * 当前版本
     */
    "currentVersion": string;

    /**
     * 最新版本（空=未获取到）
     */
    "latestVersion": string;

    /**
     * 是否有新版本
     */
    "hasUpdate": boolean;

    /**
     * State 检查状态：outdated=有新版本 / up-to-date=已是最新 / ahead=本地版本领先（非异常） / error=检查失败
     * 状态
     */
    "state": string;

    /**
     * 更新页面链接
     */
    "releaseURL": string;

    /**
     * 检查时间
     */
    "checkedAt": string;

    /**
     * 检查失败原因（空=成功）
     */
    "error": string;
}

/**
 * WinSxSAnalysis WinSxS 组件存储分析结果
 */
export interface WinSxSAnalysis {
    /**
     * 组件存储大小（字节）
     */
    "storeSize": number;

    /**
     * 可回收空间（字节）
     */
    "reclaimableSize": number;

    /**
     * 上次清理时间
     */
    "lastCleanTime": string;

    /**
     * 原始输出（前若干行）
     */
    "rawOutput": string;
}

/**
 * WinSxSCleanStatus WinSxS 后台清理状态（StartWinSxSClean / StartWinSxSCleanResetBase / GetWinSxSStatus）
 */
export interface WinSxSCleanStatus {
    /**
     * 是否正在后台清理
     */
    "running": boolean;

    /**
     * 是否已完成（无论成败）
     */
    "done": boolean;

    /**
     * 是否成功
     */
    "success": boolean;

    /**
     * 结果/错误提示
     */
    "message": string;

    /**
     * dism 原始输出（前若干行）
     */
    "output": string;

    /**
     * 开始时间（2006-01-02 15:04:05）
     */
    "startedAt": string;

    /**
     * 已耗时（秒）
     */
    "elapsedSec": number;

    /**
     * 本次是否为激进清理（/ResetBase，不可逆）
     */
    "resetBase": boolean;
}
