// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AnalyzerService 磁盘分析服务，作为 Wails v3 服务暴露给前端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * DeletePath 将文件/目录移入回收站（非永久删除）。
 * 安全保护：禁止删除磁盘根目录与系统关键目录；返回被删除对象的占用空间。
 */
export function DeletePath(path: string): $CancellablePromise<number> {
    return $Call.ByID(726286630, path);
}

/**
 * GetDirChildren 获取目录直接子级：优先 MFT 缓存，否则目录遍历（单层）
 */
export function GetDirChildren(path: string): $CancellablePromise<(models$0.FileNode | null)[] | null> {
    return $Call.ByID(3761788938, path);
}

/**
 * GetDrives 枚举所有可用逻辑磁盘及其容量信息
 */
export function GetDrives(): $CancellablePromise<models$0.DriveInfo[] | null> {
    return $Call.ByID(4245737003);
}

/**
 * OpenInExplorer 在资源管理器中打开目录（或定位选中文件）
 * 目录使用 rundll32 url.dll 协议处理器：提权进程也能以普通用户会话打开资源管理器
 * （直接 spawn explorer.exe 在提权环境下常出现窗口不显示的问题）
 */
export function OpenInExplorer(path: string): $CancellablePromise<void> {
    return $Call.ByID(2023167314, path);
}

/**
 * ScanDirectory 扫描指定目录，返回分层文件树（每层仅保留 TopN 大项 + “其他”聚合）
 */
export function ScanDirectory(opts: models$0.ScanOptions): $CancellablePromise<models$0.FileNode | null> {
    return $Call.ByID(2610985718, opts);
}

/**
 * ScanDisk 统一磁盘扫描入口（多引擎组合）：
 *   - engine=auto：管理员 + NTFS 时优先 MFT 极速扫描，否则回退目录遍历
 *   - engine=mft：强制 MFT（失败自动回退遍历并提示）
 *   - engine=walk：目录遍历（兼容所有文件系统，无需管理员）
 */
export function ScanDisk(opts: models$0.ScanOptions): $CancellablePromise<models$0.DiskScanResult> {
    return $Call.ByID(1882906190, opts);
}

/**
 * ScanMFT 以 MFT 方式扫描磁盘，返回截断树并缓存全量树
 */
export function ScanMFT(drive: string, topN: number): $CancellablePromise<models$0.FileNode | null> {
    return $Call.ByID(1911220140, drive, topN);
}
