// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CacheService 缓存清理服务，作为 Wails v3 服务暴露给前端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * AnalyzeWinSxS 分析 Windows 组件存储（WinSxS），调用 dism /AnalyzeComponentStore
 * 注：需要管理员权限，普通权限下 RawOutput 中会包含权限错误信息
 */
export function AnalyzeWinSxS(): $CancellablePromise<models$0.WinSxSAnalysis> {
    return $Call.ByID(1179312016).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CleanCache 清理选中的缓存分类（按分类名匹配）
 */
export function CleanCache(names: string[]): $CancellablePromise<models$0.CleanResult[]> {
    return $Call.ByID(327386743, names).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CleanCacheItems 针对性清理：删除勾选的具体条目（文件或整个目录）
 */
export function CleanCacheItems(categoryName: string, itemPaths: string[]): $CancellablePromise<models$0.CleanResult> {
    return $Call.ByID(3897167065, categoryName, itemPaths).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CleanWinSxS 清理 Windows 组件存储，调用 dism /StartComponentCleanup
 * 该操作可能持续数分钟至数十分钟，期间请勿关闭程序；需要管理员权限
 */
export function CleanWinSxS(): $CancellablePromise<models$0.WinSxSAnalysis> {
    return $Call.ByID(671773665).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ScanCache 扫描所有缓存分类，计算各路径占用
 */
export function ScanCache(): $CancellablePromise<models$0.CacheCategory[]> {
    return $Call.ByID(293061175).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ScanCacheDetails 查看指定缓存分类的详细内容（各路径顶层条目，按大小降序）
 */
export function ScanCacheDetails(categoryName: string): $CancellablePromise<models$0.CacheDetailPath[]> {
    return $Call.ByID(537584191, categoryName).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.WinSxSAnalysis.createFrom;
const $$createType1 = models$0.CleanResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = models$0.CacheCategory.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = models$0.CacheDetailPath.createFrom;
const $$createType6 = $Create.Array($$createType5);
