// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BackupEntry 清理备份记录（用于恢复）
 */
export class BackupEntry {
    "id": string;
    "name": string;
    "ruleType": string;
    "riskLevel": string;
    "time": string;

    /**
     * HKLM | HKCU
     */
    "regHive"?: string;

    /**
     * 注册表键路径
     */
    "regKey"?: string;

    /**
     * 值名
     */
    "regValue"?: string;

    /**
     * 原值数据
     */
    "regData"?: string;

    /**
     * 原文件/目录路径
     */
    "origPath"?: string;

    /**
     * 备份后的路径
     */
    "backedPath"?: string;

    /** Creates a new BackupEntry instance. */
    constructor($$source: Partial<BackupEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ruleType" in $$source)) {
            this["ruleType"] = "";
        }
        if (!("riskLevel" in $$source)) {
            this["riskLevel"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupEntry($$parsedSource as Partial<BackupEntry>);
    }
}
