// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RogueService 流氓软件清理服务，作为 Wails v3 服务暴露给前端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanRogue 清理选中项（registry 值删除 / 文件移入备份目录），并记录备份
 */
export function CleanRogue(ids: string[]): $CancellablePromise<models$0.RogueCleanResult[]> {
    return $Call.ByID(3946819275, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetBackups 列出所有可恢复的清理备份
 */
export function GetBackups(): $CancellablePromise<$models.BackupEntry[]> {
    return $Call.ByID(2399284493).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RestoreRogue 按 ID 恢复已清理项
 */
export function RestoreRogue(ids: string[]): $CancellablePromise<models$0.RogueCleanResult[]> {
    return $Call.ByID(3901933222, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ScanRogue 扫描流氓/推广软件组件
 */
export function ScanRogue(): $CancellablePromise<models$0.RogueItem[]> {
    return $Call.ByID(2585258155).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.RogueCleanResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.BackupEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.RogueItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
