// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MigratorService 软件迁移服务，作为 Wails v3 服务暴露给前端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetMigrations 列出所有已迁移的应用（用于恢复）
 */
export function GetMigrations(): $CancellablePromise<$models.MigrateRecord[] | null> {
    return $Call.ByID(3771079645);
}

/**
 * MoveApp 迁移应用：复制到目标盘，然后将原目录替换为目录联接
 */
export function MoveApp(srcPath: string, dstPath: string): $CancellablePromise<void> {
    return $Call.ByID(4146730520, srcPath, dstPath);
}

/**
 * RestoreApp 恢复迁移：删除联接，将目标内容移回原路径
 */
export function RestoreApp(junctionPath: string): $CancellablePromise<void> {
    return $Call.ByID(1768812493, junctionPath);
}

/**
 * ScanApps 扫描可迁移的应用目录，按大小降序返回
 */
export function ScanApps(): $CancellablePromise<models$0.MigratableApp[] | null> {
    return $Call.ByID(945803141);
}
