// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MigrateRecord 迁移记录
 */
export interface MigrateRecord {
    "id": string;

    /**
     * 应用名
     */
    "name": string;

    /**
     * 原始路径（现为联接点）
     */
    "srcPath": string;

    /**
     * 数据实际位置
     */
    "targetPath": string;
    "time": string;
}
