// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CacheCategory 缓存分类，用于前端展示与选择
 */
export class CacheCategory {
    /**
     * 分类名称
     */
    "name": string;

    /**
     * 该分类包含的缓存路径（已解析环境变量）
     */
    "paths": string[];

    /**
     * 占用空间（字节）
     */
    "size": number;

    /**
     * 文件数量
     */
    "fileCount": number;

    /**
     * 默认是否选中
     */
    "selected": boolean;

    /**
     * 路径是否存在（存在才可扫描/清理）
     */
    "exists": boolean;

    /** Creates a new CacheCategory instance. */
    constructor($$source: Partial<CacheCategory> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("selected" in $$source)) {
            this["selected"] = false;
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheCategory instance from a string or object.
     */
    static createFrom($$source: any = {}): CacheCategory {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField1_0($$parsedSource["paths"]);
        }
        return new CacheCategory($$parsedSource as Partial<CacheCategory>);
    }
}

/**
 * CacheDetailItem 缓存目录下的单个条目（文件或目录）
 */
export class CacheDetailItem {
    /**
     * 名称
     */
    "name": string;

    /**
     * 完整路径
     */
    "path": string;

    /**
     * 占用（目录为递归总大小）
     */
    "size": number;

    /**
     * 是否目录
     */
    "isDir": boolean;

    /**
     * 修改时间
     */
    "modTime": string;

    /** Creates a new CacheDetailItem instance. */
    constructor($$source: Partial<CacheDetailItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheDetailItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CacheDetailItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CacheDetailItem($$parsedSource as Partial<CacheDetailItem>);
    }
}

/**
 * CacheDetailPath 单个缓存路径的详情
 */
export class CacheDetailPath {
    /**
     * 缓存路径
     */
    "path": string;

    /**
     * 路径总占用
     */
    "size": number;

    /**
     * 文件数
     */
    "fileCount": number;

    /**
     * 顶层条目（前 N 大）
     */
    "items": CacheDetailItem[];

    /** Creates a new CacheDetailPath instance. */
    constructor($$source: Partial<CacheDetailPath> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheDetailPath instance from a string or object.
     */
    static createFrom($$source: any = {}): CacheDetailPath {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField3_0($$parsedSource["items"]);
        }
        return new CacheDetailPath($$parsedSource as Partial<CacheDetailPath>);
    }
}

/**
 * CleanResult 单分类清理结果
 */
export class CleanResult {
    /**
     * 分类名称
     */
    "category": string;

    /**
     * 释放空间（字节）
     */
    "freedBytes": number;

    /**
     * 成功删除的文件/目录数
     */
    "fileCount": number;

    /**
     * 失败项说明
     */
    "errors": string[];

    /** Creates a new CleanResult instance. */
    constructor($$source: Partial<CleanResult> = {}) {
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("freedBytes" in $$source)) {
            this["freedBytes"] = 0;
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CleanResult {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new CleanResult($$parsedSource as Partial<CleanResult>);
    }
}

/**
 * DriveInfo 逻辑磁盘信息
 */
export class DriveInfo {
    /**
     * 盘符，如 C:
     */
    "name": string;

    /**
     * 总容量（字节）
     */
    "total": number;

    /**
     * 已用（字节）
     */
    "used": number;

    /**
     * 可用（字节）
     */
    "free": number;

    /** Creates a new DriveInfo instance. */
    constructor($$source: Partial<DriveInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("used" in $$source)) {
            this["used"] = 0;
        }
        if (!("free" in $$source)) {
            this["free"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DriveInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DriveInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DriveInfo($$parsedSource as Partial<DriveInfo>);
    }
}

/**
 * FileNode 文件树节点
 */
export class FileNode {
    /**
     * 名称
     */
    "name": string;

    /**
     * 完整路径
     */
    "path": string;

    /**
     * 占用（字节）
     */
    "size": number;

    /**
     * 是否目录
     */
    "isDir": boolean;

    /**
     * 子节点（仅目录）
     */
    "children"?: (FileNode | null)[];

    /** Creates a new FileNode instance. */
    constructor($$source: Partial<FileNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FileNode {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new FileNode($$parsedSource as Partial<FileNode>);
    }
}

/**
 * MigratableApp 可迁移的应用目录
 */
export class MigratableApp {
    /**
     * 应用名
     */
    "name": string;

    /**
     * 当前路径
     */
    "path": string;

    /**
     * 占用空间
     */
    "size": number;

    /**
     * 文件数
     */
    "fileCount": number;

    /**
     * 建议迁移目标
     */
    "target": string;

    /** Creates a new MigratableApp instance. */
    constructor($$source: Partial<MigratableApp> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigratableApp instance from a string or object.
     */
    static createFrom($$source: any = {}): MigratableApp {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigratableApp($$parsedSource as Partial<MigratableApp>);
    }
}

/**
 * RogueCleanResult 清理结果
 */
export class RogueCleanResult {
    /**
     * 对应 RogueItem.ID
     */
    "id": string;

    /**
     * 是否成功
     */
    "ok": boolean;

    /**
     * 失败原因
     */
    "errMsg": string;

    /** Creates a new RogueCleanResult instance. */
    constructor($$source: Partial<RogueCleanResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("errMsg" in $$source)) {
            this["errMsg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RogueCleanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RogueCleanResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RogueCleanResult($$parsedSource as Partial<RogueCleanResult>);
    }
}

/**
 * RogueItem 流氓软件扫描结果项
 */
export class RogueItem {
    /**
     * 唯一 ID（用于清理）
     */
    "id": string;

    /**
     * 软件名
     */
    "name": string;

    /**
     * 匹配类型: registry | file | service | startup
     */
    "ruleType": string;

    /**
     * 位置描述
     */
    "location": string;

    /**
     * 具体路径/注册表值
     */
    "path": string;

    /**
     * 注册表值数据（如有）
     */
    "value": string;

    /**
     * high | medium | low
     */
    "riskLevel": string;

    /**
     * 详情
     */
    "detail": string;

    /**
     * 是否选中清理
     */
    "selected": boolean;

    /** Creates a new RogueItem instance. */
    constructor($$source: Partial<RogueItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ruleType" in $$source)) {
            this["ruleType"] = "";
        }
        if (!("location" in $$source)) {
            this["location"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("riskLevel" in $$source)) {
            this["riskLevel"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("selected" in $$source)) {
            this["selected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RogueItem instance from a string or object.
     */
    static createFrom($$source: any = {}): RogueItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RogueItem($$parsedSource as Partial<RogueItem>);
    }
}

/**
 * ScanOptions 磁盘扫描参数
 */
export class ScanOptions {
    /**
     * 扫描根路径
     */
    "path": string;

    /**
     * 最大深度（0 表示默认 3）
     */
    "maxDepth": number;

    /**
     * 每层保留的最大子节点数（0 表示默认 10）
     */
    "topN": number;

    /** Creates a new ScanOptions instance. */
    constructor($$source: Partial<ScanOptions> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("maxDepth" in $$source)) {
            this["maxDepth"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanOptions($$parsedSource as Partial<ScanOptions>);
    }
}

/**
 * WinSxSAnalysis WinSxS 组件存储分析结果
 */
export class WinSxSAnalysis {
    /**
     * 组件存储大小（字节）
     */
    "storeSize": number;

    /**
     * 可回收空间（字节）
     */
    "reclaimableSize": number;

    /**
     * 上次清理时间
     */
    "lastCleanTime": string;

    /**
     * 原始输出（前若干行）
     */
    "rawOutput": string;

    /** Creates a new WinSxSAnalysis instance. */
    constructor($$source: Partial<WinSxSAnalysis> = {}) {
        if (!("storeSize" in $$source)) {
            this["storeSize"] = 0;
        }
        if (!("reclaimableSize" in $$source)) {
            this["reclaimableSize"] = 0;
        }
        if (!("lastCleanTime" in $$source)) {
            this["lastCleanTime"] = "";
        }
        if (!("rawOutput" in $$source)) {
            this["rawOutput"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WinSxSAnalysis instance from a string or object.
     */
    static createFrom($$source: any = {}): WinSxSAnalysis {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WinSxSAnalysis($$parsedSource as Partial<WinSxSAnalysis>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CacheDetailItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FileNode.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
