// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SysService 系统信息服务，作为 Wails v3 服务暴露给前端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CheckUpdate 检查 GitHub Releases 是否有新版本。
 * 返回 UpdateInfo：包含当前/最新版本、是否有更新、发布页链接；失败时 Error 非空。
 */
export function CheckUpdate(): $CancellablePromise<models$0.UpdateInfo> {
    return $Call.ByID(2227107819);
}

/**
 * GetAppVersion 返回当前应用版本号
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(2079292231);
}

/**
 * IsAdmin 检测当前进程是否以管理员权限（elevated）运行
 */
export function IsAdmin(): $CancellablePromise<boolean> {
    return $Call.ByID(440202325);
}

/**
 * RestartAsAdmin 通过 UAC 提示以管理员身份重新启动本程序（当前实例随后自动退出）
 */
export function RestartAsAdmin(): $CancellablePromise<void> {
    return $Call.ByID(3060106476);
}
