// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AnalyzerService 磁盘分析服务，作为 Wails v3 服务暴露给前端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetDrives 枚举所有可用逻辑磁盘及其容量信息
 */
export function GetDrives(): $CancellablePromise<models$0.DriveInfo[]> {
    return $Call.ByID(4245737003).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ScanDirectory 扫描指定目录，返回分层文件树（每层仅保留 TopN 大项 + “其他”聚合）
 */
export function ScanDirectory(opts: models$0.ScanOptions): $CancellablePromise<models$0.FileNode | null> {
    return $Call.ByID(2610985718, opts).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.DriveInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.FileNode.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
