// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MigrateRecord 迁移记录
 */
export class MigrateRecord {
    "id": string;

    /**
     * 应用名
     */
    "name": string;

    /**
     * 原始路径（现为联接点）
     */
    "srcPath": string;

    /**
     * 数据实际位置
     */
    "targetPath": string;
    "time": string;

    /** Creates a new MigrateRecord instance. */
    constructor($$source: Partial<MigrateRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("srcPath" in $$source)) {
            this["srcPath"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrateRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrateRecord($$parsedSource as Partial<MigrateRecord>);
    }
}
